version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_PORT=${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - mynetwork
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'
    networks:
      - mynetwork
  maildev:
    image: maildev/maildev
    ports:
      - '1025:1025' # SMTP port
      - '1080:1080' # Web interface port
    networks:
      - mynetwork

networks:
  mynetwork:
